apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  selector:
    matchLabels:
      app: cast-service
  replicas: 3
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: wyzykiki/cast-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  selector:
    matchLabels:
      app: movie-service
  replicas: 3
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: wyzykiki/movie-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast-service:8000/api/v1/casts/